set-option -sa terminal-overrides ',xterm*:Tc'
set -g default-terminal 'tmux-256color'

unbind C-b
unbind-key o
bind C-Space send-prefix

set -g prefix C-Space

bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

set-option -g status-position top

set -g window-size largest

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @rose_pine_variant 'main'
set -g @rose_pine_variant 'main'
set -g @rose_pine_directory 'on'
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_date_time '%H:%M | %a'

set-window-option -g mode-keys vi

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @sessionx-bind 'o'
set -g @sessionx-window-mode 'on'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'
set -g @sessionx-preview-enabled 'true'

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
